apiVersion: v1
kind: Service
metadata:
  name: sample-app-loadbalancer
  namespace: cicd-demo
spec:
  selector:
    app: sample-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer